import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedRectangle13Widget7.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedGroup40Widget1.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedHeaderWidget10.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedGroup38Widget1.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedGroup36Widget1.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedGroup19Widget2.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedPilihDifabelSesuaiKondisiAndaWidget1.dart';
import 'package:flutterapp/lokerapp/generatedpilihdifabelwidget/generated/GeneratedGroup39Widget1.dart';

/* Frame pilih difabel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPilihdifabelWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1007.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 973.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 246, 252),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1007.0,
                              child: GeneratedRectangle16Widget2(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 562.0,
                              child: GeneratedRectangle13Widget7(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget10(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 100.0,
                              child: GeneratedGroup36Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 228.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 403.0,
                              child: GeneratedGroup38Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 458.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup39Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 583.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup40Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 31.0,
                              child:
                                  GeneratedPilihDifabelSesuaiKondisiAndaWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 883.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 90.0,
                              child: GeneratedGroup19Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
