import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedGroup56Widget4.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedRectangle19Widget12.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedGroup61Widget1.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedHeaderWidget11.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedVectorWidget80.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedVectorWidget82.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedRectangle21Widget2.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedGroup63Widget1.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedGroup60Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedGroup19Widget3.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedSiapmelayanipengaduanandaWidget.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedGroup62Widget1.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedRectangle20Widget4.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedRectangle18Widget8.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedVectorWidget81.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedGroup64Widget2.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedLayananPengaduanWidget.dart';
import 'package:flutterapp/lokerapp/generatedlaporanwidget/generated/GeneratedRectangle13Widget8.dart';

/* Frame laporan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLaporanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 973.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 973.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 28, 62, 252),
                              ),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 135.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 700.0,
                              child: GeneratedRectangle13Widget8(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget11(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 77.0,
                              right: null,
                              bottom: null,
                              width: 237.0,
                              height: 31.0,
                              child: GeneratedLayananPengaduanWidget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 733.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 65.0,
                              child: GeneratedGroup56Widget4(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 227.0,
                              height: 20.0,
                              child: GeneratedSiapmelayanipengaduanandaWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup60Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 290.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup61Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup62Widget1(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 412.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 122.0,
                              child: GeneratedGroup64Widget2(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 556.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 154.0,
                              child: GeneratedGroup63Widget1(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 308.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedRectangle18Widget8(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 369.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedRectangle19Widget12(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedRectangle20Widget4(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 26.0,
                              child: GeneratedRectangle21Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.036495600905373834;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        15.6201171875;

                                double percentHeight = 0.01036782181397739;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        10.087890625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.10981308411214953,
                                      translateY: constraints.maxHeight *
                                          0.32476875642343267,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget80())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.036495600905373834;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        15.6201171875;

                                double percentHeight = 0.01036782181397739;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        10.087890625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.10981308411214953,
                                      translateY: constraints.maxHeight *
                                          0.4501541623843782,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget81())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.036495600905373834;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        15.6201171875;

                                double percentHeight = 0.01036782181397739;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        10.087890625;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.10981308411214953,
                                      translateY: constraints.maxHeight *
                                          0.512846865364851,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget82())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 883.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 90.0,
                              child: GeneratedGroup19Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
