import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedHeaderWidget6.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedRectangle18Widget4.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup72Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedUnnamed1Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup65Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup68Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup57Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedPriaMinPendD3Usia20thn30thnFamiliarsalesforcedanpengala.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedGroup73Widget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedDeskripsiPekerjaanWidget.dart';
import 'package:flutterapp/lokerapp/generatedpilihanpekerjaanwidget/generated/GeneratedCallCenterTravelWidget1.dart';

/* Frame pilihan pekerjaan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPilihanpekerjaanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1007.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 973.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 246, 252),
                              ),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget6(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 284.0,
                              child: GeneratedRectangle18Widget4(),
                            ),
                            Positioned(
                              left: 134.0,
                              top: 139.0,
                              right: null,
                              bottom: null,
                              width: 194.0,
                              height: 29.0,
                              child: GeneratedCallCenterTravelWidget1(),
                            ),
                            Positioned(
                              left: 132.0,
                              top: 337.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 32.0,
                              child: GeneratedGroup57Widget(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 136.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 90.0,
                              child: GeneratedUnnamed1Widget(),
                            ),
                            Positioned(
                              left: 135.0,
                              top: 224.0,
                              right: null,
                              bottom: null,
                              width: 183.0,
                              height: 24.0,
                              child: GeneratedGroup68Widget(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 187.0,
                              right: null,
                              bottom: null,
                              width: 139.0,
                              height: 20.0,
                              child: GeneratedGroup65Widget(),
                            ),
                            Positioned(
                              left: 134.0,
                              top: 186.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 22.0,
                              child: GeneratedGroup66Widget(),
                            ),
                            Positioned(
                              left: 134.0,
                              top: 276.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 25.0,
                              child: GeneratedGroup72Widget(),
                            ),
                            Positioned(
                              left: 233.0,
                              top: 276.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 25.0,
                              child: GeneratedGroup73Widget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 216.0,
                              height: 29.0,
                              child: GeneratedDeskripsiPekerjaanWidget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 723.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 284.0,
                              child: GeneratedGroup70Widget(),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 443.0,
                              right: null,
                              bottom: null,
                              width: 372.0,
                              height: 235.0,
                              child:
                                  GeneratedPriaMinPendD3Usia20thn30thnFamiliarsalesforcedanpengala(),
                            ),
                            Positioned(
                              left: 310.0,
                              top: 337.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 32.0,
                              child: GeneratedGroup69Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
