import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedHeaderWidget2.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup4Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedEmploymentLogoBackgroundPNGImage2Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/lokerapp/generatedsignupwidget1/generated/GeneratedEmploymentLogoBackgroundPNGImage3Widget.dart';

/* Frame Signup
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 246, 252),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 480.0,
                              child: GeneratedRectangle12Widget1(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget2(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 658.0,
                              child: GeneratedGroup25Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 303.0,
                              height: 59.0,
                              child: GeneratedGroup3Widget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 428.0,
                              right: null,
                              bottom: null,
                              width: 303.0,
                              height: 59.0,
                              child: GeneratedGroup4Widget1(),
                            ),
                            Positioned(
                              left: 58.0,
                              top: 515.0,
                              right: null,
                              bottom: null,
                              width: 303.0,
                              height: 59.0,
                              child: GeneratedGroup5Widget(),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 602.0,
                              right: null,
                              bottom: null,
                              width: 303.0,
                              height: 59.0,
                              child: GeneratedGroup24Widget(),
                            ),
                            Positioned(
                              left: 92.0,
                              top: 258.0,
                              right: null,
                              bottom: null,
                              width: 238.0,
                              height: 44.0,
                              child: GeneratedGroup27Widget(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 688.0,
                              right: null,
                              bottom: null,
                              width: 357.0,
                              height: 30.0,
                              child: GeneratedGroup17Widget(),
                            ),
                            Positioned(
                              left: 116.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 196.0,
                              height: 196.0,
                              child:
                                  GeneratedEmploymentLogoBackgroundPNGImage2Widget1(),
                            ),
                            Positioned(
                              left: 116.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 192.0,
                              height: 192.0,
                              child:
                                  GeneratedEmploymentLogoBackgroundPNGImage3Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
