import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedGroup38Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedGroup19Widget1.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedRectangle13Widget6.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedPilihDifabelSesuaiKondisiAndaWidget.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedHeaderWidget9.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomepilihdifabelwidget/generated/GeneratedGroup40Widget.dart';

/* Frame home pilih difabel
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepilihdifabelWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1007.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 973.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 246, 252),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 1007.0,
                              child: GeneratedRectangle16Widget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 141.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 719.0,
                              child: GeneratedRectangle13Widget6(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget9(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 100.0,
                              child: GeneratedGroup36Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 228.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 524.0,
                              child: GeneratedGroup38Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 419.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 100.0,
                              child: GeneratedGroup39Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 544.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 100.0,
                              child: GeneratedGroup40Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 669.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 100.0,
                              child: GeneratedGroup41Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 381.0,
                              height: 31.0,
                              child:
                                  GeneratedPilihDifabelSesuaiKondisiAndaWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 883.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 90.0,
                              child: GeneratedGroup19Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
