import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedkirimlamaranlanjutanwidget/generated/GeneratedGroup25Widget2.dart';
import 'package:flutterapp/lokerapp/generatedkirimlamaranlanjutanwidget/generated/GeneratedGroup56Widget1.dart';
import 'package:flutterapp/lokerapp/generatedkirimlamaranlanjutanwidget/generated/GeneratedEmploymentLogoBackgroundPNGImage2Widget3.dart';
import 'package:flutterapp/lokerapp/generatedkirimlamaranlanjutanwidget/generated/GeneratedEmploymentLogoBackgroundPNGImage3Widget2.dart';
import 'package:flutterapp/lokerapp/generatedkirimlamaranlanjutanwidget/generated/GeneratedInformasipenerimaanakankamikirimmelaluiemailandaWidget.dart';
import 'package:flutterapp/lokerapp/generatedkirimlamaranlanjutanwidget/generated/GeneratedRectangle12Widget3.dart';
import 'package:flutterapp/lokerapp/generatedkirimlamaranlanjutanwidget/generated/GeneratedHeaderWidget4.dart';

/* Frame kirimlamaranlanjutan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKirimlamaranlanjutanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 246, 252),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 480.0,
                              child: GeneratedRectangle12Widget3(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget4(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 232.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 612.0,
                              child: GeneratedGroup25Widget2(),
                            ),
                            Positioned(
                              left: 116.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 196.0,
                              height: 196.0,
                              child:
                                  GeneratedEmploymentLogoBackgroundPNGImage2Widget3(),
                            ),
                            Positioned(
                              left: 116.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 192.0,
                              height: 192.0,
                              child:
                                  GeneratedEmploymentLogoBackgroundPNGImage3Widget2(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 303.0,
                              right: null,
                              bottom: null,
                              width: 224.0,
                              height: 450.0,
                              child:
                                  GeneratedInformasipenerimaanakankamikirimmelaluiemailandaWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 647.0,
                              right: null,
                              bottom: null,
                              width: 265.0,
                              height: 65.0,
                              child: GeneratedGroup56Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
