import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedlogowidget/generated/GeneratedEmploymentLogoBackgroundPNGImage1Widget.dart';
import 'package:flutterapp/lokerapp/generatedlogowidget/generated/GeneratedEmploymentLogoBackgroundPNGImage2Widget.dart';
import 'package:flutterapp/lokerapp/generatedlogowidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Frame logo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLoginWidget'),
      child: Container(
        decoration: BoxDecoration(
          boxShadow: kIsWeb
              ? []
              : [
                  BoxShadow(
                    color: Color.fromARGB(63, 0, 0, 0),
                    offset: Offset(0.0, 4.0),
                    blurRadius: 4.0,
                  )
                ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 926.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 428.0,
                          height: 926.0,
                          child: Stack(
                              clipBehavior: Clip.none,
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 255, 255, 255),
                                  ),
                                ),
                                Positioned(
                                  left: 31.0,
                                  top: 13.0,
                                  right: null,
                                  bottom: null,
                                  width: 380.0,
                                  height: 20.0,
                                  child: GeneratedHeaderWidget(),
                                ),
                                Positioned(
                                  left: 104.0,
                                  top: 313.0,
                                  right: null,
                                  bottom: null,
                                  width: 220.0,
                                  height: 220.0,
                                  child:
                                      GeneratedEmploymentLogoBackgroundPNGImage1Widget(),
                                ),
                                Positioned(
                                  left: 104.0,
                                  top: 313.0,
                                  right: null,
                                  bottom: null,
                                  width: 220.0,
                                  height: 220.0,
                                  child:
                                      GeneratedEmploymentLogoBackgroundPNGImage2Widget(),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
        ),
      ),
    ));
  }
}
