import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedHeaderWidget5.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedKategoriPekerjaanPopulerWidget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedGroup32Widget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/Generated5PositionOpenWidget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedSoftwareDeveloperWidget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedJenisDifabelYangDipilihWidget.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedGroup56Widget2.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedRectangle13Widget4.dart';
import 'package:flutterapp/lokerapp/generatedhomewidget/generated/GeneratedEllipse2Widget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1731.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 1731.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 246, 252),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 545.0,
                              child: GeneratedRectangle16Widget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 624.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 324.0,
                              child: GeneratedRectangle18Widget1(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 245.0,
                              height: 26.0,
                              child: GeneratedJenisDifabelYangDipilihWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 324.0,
                              child: GeneratedRectangle13Widget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04205607476635514;

                                final double height = constraints.maxHeight *
                                    0.012709416522241479;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8808411214953271,
                                      y: constraints.maxHeight *
                                          0.16522241478913924,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup31Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 196.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 43.0,
                              child: GeneratedGroup28Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 277.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 43.0,
                              child: GeneratedGroup29Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 373.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 65.0,
                              child: GeneratedGroup56Widget2(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 29.0,
                              child: GeneratedKategoriPekerjaanPopulerWidget(),
                            ),
                            Positioned(
                              left: 150.0,
                              top: 649.0,
                              right: null,
                              bottom: null,
                              width: 128.0,
                              height: 128.0,
                              child: GeneratedEllipse2Widget(),
                            ),
                            Positioned(
                              left: 128.0,
                              top: 806.0,
                              right: null,
                              bottom: null,
                              width: 216.0,
                              height: 29.0,
                              child: GeneratedSoftwareDeveloperWidget(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 843.0,
                              right: null,
                              bottom: null,
                              width: 144.0,
                              height: 21.0,
                              child: Generated5PositionOpenWidget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 999.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 324.0,
                              child: GeneratedGroup32Widget(),
                            ),
                            Positioned(
                              left: 9.0,
                              top: 1365.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 324.0,
                              child: GeneratedGroup33Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04205613269984165;

                                final double height =
                                    constraints.maxHeight * 0.01039861021256736;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8808411214953271,
                                      y: constraints.maxHeight *
                                          0.11842865395725015,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup30Widget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
