import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedLamaranPekerjaanWidget.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedGroup60Widget.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedGroup56Widget3.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedRectangle13Widget5.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedGroup63Widget.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedHeaderWidget8.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedLengkapidataberikutWidget.dart';
import 'package:flutterapp/lokerapp/generatedlamarpekerjaanwidget/generated/GeneratedGroup61Widget.dart';

/* Frame lamarpekerjaan
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLamarpekerjaanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 973.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 973.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 28, 62, 252),
                              ),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 135.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 700.0,
                              child: GeneratedRectangle13Widget5(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget8(),
                            ),
                            Positioned(
                              left: 104.0,
                              top: 77.0,
                              right: null,
                              bottom: null,
                              width: 224.0,
                              height: 31.0,
                              child: GeneratedLamaranPekerjaanWidget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 733.0,
                              right: null,
                              bottom: null,
                              width: 367.0,
                              height: 65.0,
                              child: GeneratedGroup56Widget3(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 171.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 21.0,
                              child: GeneratedLengkapidataberikutWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup60Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup61Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 429.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 61.0,
                              child: GeneratedGroup62Widget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 529.0,
                              right: null,
                              bottom: null,
                              width: 379.0,
                              height: 154.0,
                              child: GeneratedGroup63Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 883.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 90.0,
                              child: GeneratedGroup19Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
