import 'package:flutter/material.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedGroup86Widget.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/lokerapp/generatedloginwidget/generated/GeneratedGroup3Widget.dart';

/* Frame Login 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 247, 245, 251),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 480.0,
                              child: GeneratedRectangle12Widget(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 380.0,
                              height: 20.0,
                              child: GeneratedHeaderWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 405.0,
                              child: GeneratedGroup21Widget(),
                            ),
                            Positioned(
                              left: 97.0,
                              top: 309.0,
                              right: null,
                              bottom: null,
                              width: 236.0,
                              height: 44.0,
                              child: GeneratedGroup22Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 391.0,
                              right: null,
                              bottom: null,
                              width: 289.0,
                              height: 61.0,
                              child: GeneratedGroup3Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 289.0,
                              height: 61.0,
                              child: GeneratedGroup4Widget(),
                            ),
                            Positioned(
                              left: 230.0,
                              top: 550.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 21.0,
                              child: GeneratedForgotPasswordWidget(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 44.0,
                              child: GeneratedGroup86Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
